In [45]:
import pandas as pd

In [46]:
pd.__version__

'2.2.2'

In [47]:
df=pd.read_csv('laptops.csv')

In [48]:
df.shape

(2160, 12)

In [49]:
df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

In [50]:
len(df['Brand'].unique())

27

In [51]:
df.columns[df.isnull().any()]

Index(['Storage type', 'GPU', 'Screen'], dtype='object')

In [52]:
df['Final Price'][df['Brand']=='Dell'].max()

3936.0

In [53]:
df['Screen'].median()

15.6

In [54]:
df['Screen'].mode()

0    15.6
Name: Screen, dtype: float64

In [55]:
df['Screen'] = df['Screen'].fillna(value=15.6)

In [56]:
df['Screen'].median()

15.6

In [57]:
import numpy as np

In [58]:
X = df[['RAM', 'Storage', 'Screen']][df['Brand']=='Innjoo'].values

In [59]:
X_transpose = X.T

In [60]:
XTX = np.dot(X_transpose, X)

In [61]:
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [62]:
inverse_matrix = np.linalg.inv(XTX)

In [63]:
inverse_matrix

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [64]:
y = np.array([1100, 1300, 800, 900, 1000, 1100])

In [65]:
y

array([1100, 1300,  800,  900, 1000, 1100])

In [70]:
w = (inverse_matrix.dot(X.T)).dot(y).sum()

In [71]:
w

91.29988062995815